### ISSUE TITLE
Website doesn't work

### ISSUE THREAD

**Issue by TollyH** [Shuttleu/FBITicket#1]
Get cloudfare error 523 origin is unreachable

**Comment by Shuttleu** [comment]
Had an issue with the server, should be back up now

**Comment by TollyH** [comment]
Still not up at the moment, but I'll give it a while and let you know if it's still not up

**Comment by TollyH** [comment]
Yep it's working fine now!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
